src/main/java/sv/edu/uesocc/ingenieria/prn335_2017/web/controladores/GenericManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.uesocc.ingenieria.prn335_2017.web.controladores;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.acceso.GenericFacadeLocal;

/**
 *
 * @author carlos
 */
public abstract class GenericManagedBean<T> implements Serializable {

    List<T> listaDatos;

    /**
     * Este metodo sirve para crear un nuevo un registro
     */
    public void crear() {
        if (getFacadeLocal() != null) {
            try {
                System.out.println("Llego aqui");
                getFacadeLocal().create(getEntity());
                llenarLista();
                enviarMensaje(false,"Registro creado correctamente.");
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
                enviarMensaje(true,"Error al crear registro creado correctamente.");
            }
        }
    }

    /**
     * Este metodo sirve para editar un registro
     */
    public void editar() {
        if (getFacadeLocal() != null) {
            try {
                System.out.println("Llego aqui");
                getFacadeLocal().edit(getEntity());
                llenarLista();
                enviarMensaje(false,"Edicion realizada correctamente.");
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
                enviarMensaje(true,"Error al editar registro.");
            }
        }
    }

    /**
     * Este metodo sirve para eliminar un registro
     */
    public void eliminar() {
        if (getFacadeLocal() != null) {
            try {
                System.out.println("Llego aqui");
                getFacadeLocal().remove(getEntity());
                llenarLista();
                enviarMensaje(false,"Registro eliminado correctamente");
            } catch (Exception ex) {
                System.out.println("Error: " + ex);
                enviarMensaje(true,"Error al eliminar registro");
            }
        }
    }

    /**
     * Este metodo sirve para llenar una lista de datos obtenidos de la base de
     * datos
     */
    public void llenarLista() {
        if (getFacadeLocal().findAll() != null) {
            this.listaDatos = getFacadeLocal().findAll();
        } else {
            this.listaDatos = Collections.EMPTY_LIST;
        }
    }

    /**
     * Este metodo sirve para mostrar un mensaje en el JSF
     *
     * @param error espera un true o false para mostrar un mensaje de error o
     * confirmacion respectivaente
     * @param mensaje espera el mensaje a mostrar
     */
    public void enviarMensaje(boolean error, String mensaje) {
        if (error=false) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Info", mensaje));
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Info", mensaje));
        }
    }

    /**
     * 
     * @return se espera que retorne el una interfaz de algun tipo para trabajar con ell
     */
    protected abstract GenericFacadeLocal<T> getFacadeLocal();

    /**
     *
     * @return se espera que retorne una entitdad para trabajar con ella
     */
    public abstract T getEntity();

}

src/main/java/sv/edu/uesocc/ingenieria/prn335_2017/web/controladores/SesionDeUsuarioBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.uesocc.ingenieria.prn335_2017.web.controladores;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.Local;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;

/**
 *
 * @author carlos
 */
@Named
@SessionScoped
public class SesionDeUsuarioBean implements Serializable{
    
    private String codigoIdioma="es";
    private static Map<String,Object> paises;
    
    static{
    paises=new LinkedHashMap<>();
    paises.put("Español", Locale.forLanguageTag("es"));
    paises.put("English",Locale.US);
    }

    public  Map<String, Object> getPaises() {
        return paises;
    }

    public String getCodigoIdioma() {
        return codigoIdioma;
    }

    public void setCodigoIdioma(String codigoIdioma) {
        this.codigoIdioma = codigoIdioma;
    }
    
    public void CambioDeIdiomaHandler(ValueChangeEvent vce){
        if(vce.getNewValue()!=null){
            try {
                String nuevoCodigo=vce.getNewValue().toString();
                for (Map.Entry<String, Object> entrySet : paises.entrySet()) {
                   
                    Locale value = (Locale) entrySet.getValue();
                    if(value.toString().compareTo(nuevoCodigo)==0){
                        FacesContext.getCurrentInstance().getViewRoot().setLocale(value);
                        return;
                        
                    }
                    
                }
            } catch (Exception ex) {
                Logger.getLogger(getClass().getName()).log(Level.SEVERE,ex.getMessage(), ex);
            }
  
            
        }
    }
    /**
     *
     * @param clave
     * @return
     */
    public String getMensaje(final String clave){
        try {
            ResourceBundle propiedades = FacesContext.getCurrentInstance().getApplication().getResourceBundle(FacesContext.getCurrentInstance(),"PropiedadesGenerales");
            if(propiedades!=null && propiedades.containsKey(clave)){
                return propiedades.getString(clave);
            }
        } catch (Exception ex) {
             Logger.getLogger(getClass().getName()).log(Level.SEVERE, ex.getMessage(),ex);
        }
     return null;   
}
    
}

src/main/java/sv/edu/uesocc/ingenieria/prn335_2017/web/controladores/TipoPostBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.uesocc.ingenieria.prn335_2017.web.controladores;

import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import org.primefaces.event.SelectEvent;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.acceso.GenericFacadeLocal;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.acceso.TipoPostFacadeLocal;
import sv.edu.uesocc.ingenieria.prn335_2017.datos.definiciones.TipoPost;

/**
 *
 * @author carlos
 */
@Named(value = "tipoPostBean")
@ViewScoped
public class TipoPostBean extends GenericManagedBean<TipoPost> implements Serializable {

    /**
     * Creates a new instance of TipoPostBean
     */
    public TipoPostBean() {
    }
    
    
 @EJB
    TipoPostFacadeLocal facade;
    TipoPost tipopostEntity;
    boolean btnVisible=false;
    
    
    
 
    public TipoPostFacadeLocal  getFacade(){
    return facade;
    }
    
     public boolean isBtnVisible() {
        return btnVisible;
    }
    
     public void setBtnVisible(boolean btnVisible) {
        this.btnVisible = btnVisible;
    }
     
     public void setFacade(TipoPostFacadeLocal facade){
     this.facade=facade;
     }
     
     public TipoPost getTipoPostEntity(){
     return tipopostEntity;
     }
     
     public  void setTipoPostEntity(TipoPost tipopostEntity){
     this.tipopostEntity= tipopostEntity;
     }
     
     public List<TipoPost> getListaDatos(){
     return listaDatos;
     }
     
     public void setListaDatos(List<TipoPost> listaDatos){
         this.listaDatos=listaDatos;
     }
     
     
    

     
    @Override
    public TipoPost getEntity(){
    return tipopostEntity;
    }
    
    @Override
     protected GenericFacadeLocal<TipoPost> getFacadeLocal() {
        return facade;
    }
     
      @Override
    public void editar() {
        super.editar(); 
        reiniciarValores();
    }

    @Override
    public void eliminar() {
        super.eliminar(); 
        reiniciarValores();
    }

    @Override
    public void crear() {
        super.crear(); 
        reiniciarValores();
    }

    
     @PostConstruct
    public void init(){
        llenarLista();
    }
    
    
    public void onRowSelect(SelectEvent event) {
        btnVisible = true;
    }
    
    public void btnCancelar() {
        tipopostEntity = new TipoPost();
        btnVisible = false;
        
    }
    
    public void reiniciarValores(){
        tipopostEntity.setActivo(false);
        tipopostEntity.setDescripcion(null);
        tipopostEntity.setNombre(null);
    }
      
   
    
}

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pr="http://xmlns.jcp.org/jsf/composite/prn335"
      xmlns:co="http://xmlns.jcp.org/jsf/composite/composite">
    <h:head>
        <title>#{msg['generador.titulo']}</title>
    </h:head>
    <h:body>
        
           
                    <p:layoutUnit position="north" resizable="false" closable="false" collapsible="false">
                        <h:form id="frmtop">
                            <p:panelGrid columns="4">
                                <h:outputLabel for="lstIdiomas" value="#{msg['generador.idioma']}" />
                                <h:selectOneListbox id="lstidiomas" value="#{sesionDeUsuarioBean.codigoIdioma}" size="2" valueChangeListener="#{sesionDeUsuarioBean.CambioDeIdiomaHandler}" onchange="submit()">
                                    <f:selectItems value="#{sesionDeUsuarioBean.paises}"/>
                                </h:selectOneListbox>
                            </p:panelGrid>
                        </h:form> 
                    </p:layoutUnit>
             
        
        
        <f:view>
            <h:form id="tabla">
                <h1 align="center"><h:outputText value="#{msg['generador.titulo']}"/></h1>
                <p:dataTable value="#{tipoPostBean.listaDatos}" var="item" paginator="true" rows="5" rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{tipoPostBean.tipoPostEntity}" rowKey="#{item.idTipoPost}">
                    <p:ajax event="rowSelect" listener="#{tipoPostBean.onRowSelect}" update=":formulario"/>
                    <p:column sortBy="#{item.idTipoPost}">
                        <f:facet name="header">
                            <h:outputText value="#{msg['generador.columna1']}"/>
                        </f:facet>
                            <h:outputText value="#{item.idTipoPost}"/>
                    </p:column> 
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{msg['generador.columna2']}"/>
                        </f:facet>
                        <h:outputText value="#{item.nombre}"/>
                    </p:column> 
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{msg['generador.columna3']}"/>
                        </f:facet>
                        <h:outputText value="#{item.activo}"/>
                    </p:column> 
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="#{msg['generador.columna4']}"/>
                        </f:facet>
                        <h:outputText value="#{item.descripcion}"/>
                    </p:column>    
                </p:dataTable>
            </h:form>
        </f:view> 
        <f:view>
            <h:form id="formulario" >
                <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
                <div align="left">
                    <p:panelGrid columns="2">
                        <p:outputLabel value="#{msg['generador.columna2']}:" for="nombre" />
                        <p:inputText id="nombre" value="#{tipoPostBean.tipoPostEntity.nombre}" title="Nombre" required="true" requiredMessage="#{msg['generador.nombre']}"/>
                        <p:outputLabel value="#{msg['generador.columna3']}:" for="activo" />
                        <p:selectBooleanCheckbox id="activo" value="#{tipoPostBean.tipoPostEntity.activo}" />
                        <p:outputLabel value="#{msg['generador.columna4']}:" for="descripcion" />
                        <p:inputText id="descripcion" value="#{tipoPostBean.tipoPostEntity.descripcion}" title="Descripcion" required="true" requiredMessage="#{msg['generador.descripcion']}"/>
                    </p:panelGrid>
                    <pr:botonesgua compo="#{tipoPostBean}"/>
                    <co:botoneseli generador="#{tipoPostBean}"/>
                </div>
            </h:form>
        </f:view>
        <br/>
        <p align="left" style="size: 10px">#{msg['generador.final']}</p>
        
    </h:body>
</html>

src/main/webapp/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>